Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"  # Ubuntu 22.04 LTS
    config.vm.network "private_network", type: "dhcp"
  
    # SERVER
    config.vm.define "tkaragozS" do |server|
      server.vm.hostname = "tkaragozS"
      server.vm.network "private_network", ip: "192.168.56.110"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
      server.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install -y curl
        curl -sfL https://get.k3s.io | sh -
      SHELL
    end
  
    # SERVERWORKER
    config.vm.define "tkaragozSW" do |worker|
      worker.vm.hostname = "tkaragozSW"
      worker.vm.network "private_network", ip: "192.168.56.111"
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
      worker.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install -y curl
        curl -sfL https://get.k3s.io | K3S_URL="https://192.168.56.110:6443" K3S_TOKEN="NODE_TOKEN" sh -
      SHELL
    end
  end
  